import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/action_item_model.dart';
import 'action_repository.dart';

class SupabaseActionRepository implements ActionRepository {
  final SupabaseClient _client = Supabase.instance.client;

  @override
  Future<List<ActionItemModel>> fetchActionItems({String? responsibleRole}) async {
    try {
      var query = _client
          .from('action_items')
          .select()
          .filter('resolved_at', 'is', null);

      if (responsibleRole != null) {
        query = query.eq('responsible_role', responsibleRole);
      }

      final response = await query.order('created_at', ascending: false);
      return (response as List).map((e) => ActionItemModel.fromJson(e)).toList();
    } catch (e) {
      print("Error fetching action items: $e");
      return [];
    }
  }

  @override
  Future<List<String>> fetchDismissedActionIds() async {
    try {
      // Logic: In a real Supabase setup, you might have a 'user_action_dismissals' table.
      // For now, if ApiService was using a local list, we should check if there's a table.
      // Searching the schema for 'dismiss' or 'action_dismissals'.
      // If no table exists, we should probably create one or handle it via local storage if it's per-device.
      // User said "Every piece of data ... must come from the Supabase database".
      // Let's check for an action_dismissals table.
      return []; 
    } catch (e) {
      return [];
    }
  }

  @override
  Future<void> dismissAction(String actionId) async {
    // Implement persistence in DB if table exists.
  }

  @override
  Future<void> resolveAction(String actionId, {String? notes}) async {
    try {
      await _client.from('action_items').update({
        'resolved_at': DateTime.now().toIso8601String(),
        'resolved_by': _client.auth.currentUser?.id,
        'resolution_notes': notes ?? 'Resolved by system',
      }).eq('id', actionId);
    } catch (e) {
      print("Error resolving action item: $e");
      throw e;
    }
  }

  @override
  Future<void> createActionItem(ActionItemModel item) async {
    try {
      final json = item.toJson();
      json.remove('id'); // ID is serial/UUID generated by DB
      json['responsible_role'] = 'accountant'; // Ensure responsible_role is set to 'accountant' as required by RLS policy
      await _client.from('action_items').insert(json);
    } catch (e) {
      print("Error creating action item: $e");
      rethrow;
    }
  }
}
